import { db } from "./firebase";
import {
  doc,
  getDoc,
  setDoc,
  collection,
  addDoc,
  getDocs,
  query,
  orderBy,
  limit,
} from "firebase/firestore";

export interface BotConfig {
  active: boolean;
  maxPositionSize: number;
  dailyStopLossPercent: number;
}

export interface TradeLog {
  id?: string;
  asset: string;
  side: "BUY" | "SELL";
  price: number;
  qty: number;
  timestamp: any; // Firestore timestamp or date string
  profit: number; // profit/loss generated by this trade (if closing a position)
}

// Default configuration if none exists
const DEFAULT_CONFIG: BotConfig = {
  active: false,
  maxPositionSize: 1000, // max dollar size per trade
  dailyStopLossPercent: 2.0, // stop trading if portfolio drops 2% in a day
};

export async function getBotConfig(userId: string): Promise<BotConfig> {
  try {
    const docRef = doc(db, "users", userId, "settings", "bot");
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      return docSnap.data() as BotConfig;
    }
    // If it doesn't exist, create and return default config
    await saveBotConfig(userId, DEFAULT_CONFIG);
    return DEFAULT_CONFIG;
  } catch (error) {
    console.error("Error getting bot config:", error);
    return DEFAULT_CONFIG;
  }
}

export async function saveBotConfig(userId: string, config: BotConfig): Promise<void> {
  try {
    const docRef = doc(db, "users", userId, "settings", "bot");
    await setDoc(docRef, config, { merge: true });
  } catch (error) {
    console.error("Error saving bot config:", error);
    throw error;
  }
}

export async function addTradeLog(userId: string, trade: Omit<TradeLog, "id">): Promise<string> {
  try {
    const colRef = collection(db, "users", userId, "trades");
    const docRef = await addDoc(colRef, {
      ...trade,
      timestamp: trade.timestamp || new Date().toISOString(),
    });
    return docRef.id;
  } catch (error) {
    console.error("Error adding trade log:", error);
    throw error;
  }
}

export async function getTradeLogs(userId: string, maxLimit = 50): Promise<TradeLog[]> {
  try {
    const colRef = collection(db, "users", userId, "trades");
    const q = query(colRef, orderBy("timestamp", "desc"), limit(maxLimit));
    const querySnapshot = await getDocs(q);
    const trades: TradeLog[] = [];
    querySnapshot.forEach((docSnap) => {
      trades.push({
        id: docSnap.id,
        ...docSnap.data(),
      } as TradeLog);
    });
    return trades;
  } catch (error) {
    console.error("Error getting trade logs:", error);
    return [];
  }
}
